from strategies.strategy import Strategy
from strategies.munkres_strategy import MunkresStrategy
from strategies.distance_optimal_strategy import DistanceOptimalStrategy
from strategies.constraints_strategy import ConstraintsStrategy